### PR TITLE
rl/add height weight

### PR DESCRIPTION
**Pull request by renelabounek**
@jcohenadad  and @alexfoias, I have updated participants.tsv file about available height and weight records and submit this PR.

We only miss records from tehran, which might come after New Year, and 2 of 6 records from perform.

tokyo* submissions has uploaded data of 7 same subjects acquired at 3 different scanners. I am not sure, if this important fact is recorded somewhere.

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
This will conflict with #97.

I suggest we first merge this branch, and then #97.

**Review by jcohenadad — APPROVED** [review]
Thank you for doing this @renelabounek

**Comment by alexfoias** [comment]
@renelabounek thank you for your help. Regarding the tokyo* submissions, we are talking of the same subjects, but on different sites. That was my understanding, @jcohenadad can confirm.

**Comment by jcohenadad** [comment]
> tokyo* submissions has uploaded data of 7 same subjects acquired at 3 different scanners. I am not sure, if this important fact is recorded somewhere.

not properly recorded and this is indeed a problem-- related to https://github.com/spine-generic/data-multi-subject/issues/102

**Comment by renelabounek** [comment]
Is there some pending reason why data have not been merged to the master version yet? Or is it stucked again on some robot process from fork into master?

**Comment by jcohenadad** [comment]
> Is there some pending reason why data have not been merged to the master version yet? Or is it stucked again on some robot process from fork into master?

The PR was not merged 😉 

Now fixed

**Pull request merged**
