### PR TITLE
Fix broken link to analysis instructions

### PR DESCRIPTION
**Pull request by valosekj**
This PR fixes broken link to analysis instructions on the readthedocs website.

### CODE REVIEW

**Review by jcohenadad — APPROVED** [review]
thank you!

**Comment by valosekj** [comment]
Travis failed from unknown reason for me.
It happened during spine-generic dependency installation (matplotlib):
https://travis-ci.com/github/spine-generic/data-multi-subject/builds/202370396#L203-L204

I have just tried to install spine-generic on my machine and it works without any problems:
```
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install spine-generic@git+https://github.com/spine-generic/spine-generic.git@v2.3
```

**Comment by jcohenadad** [comment]
connection issue: https://travis-ci.com/github/spine-generic/data-multi-subject/builds/202370396#L222

i've restarted the job, let's see...

**Comment by valosekj** [comment]
Thank you 👍🏻 Travis has finished successfully this time. Can I merge this PR?

**Pull request merged**
