### PR TITLE
Rename MTS suffix

### PR DESCRIPTION
**Pull request by sandrinebedard**
# Description
This PR addresses #116 . It renames all MTS files to be BIDS compatible:

```
acq-MTon_MTS → flip-1_mt-on_MTS
acq-MToff_MTS → flip-1_mt-off_MTS
acq-T1w_MTS → flip-2_mt-off_MTS
```

### CODE REVIEW

**Comment by mguaypaq** [comment]
The change itself looks good (that is, it looks like you correctly renamed all the files). The _Dataset Validator_ check is failing, though. I re-ran it several times because of some transient issues (`scikit-learn` versus `sklearn` in some dependency, temporary network problem while downloading from `amazon`), but [this run](https://github.com/spine-generic/data-multi-subject/actions/runs/3933564033/jobs/6764815090#step:13:1) looks like it's an actual issue:

```
sg_params_checker -path-in ./
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/bin/sg_params_checker", line 11, in <module>
    load_entry_point('spinegeneric==2.5.dev0', 'console_scripts', 'sg_params_checker')()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/spinegeneric/cli/params_checker.py", line 86, in main
    MTS_acq = item.filename.split("_acq-")[1].split(".")[0]
IndexError: list index out of range
```

It looks like the `params_checker` is [using the old filename format](https://github.com/spine-generic/spine-generic/blob/3aa69465063d823088b2c819d3ad9b81725b2fc8/spinegeneric/cli/params_checker.py#L86). I'll make a (backwards-compatible) fix upstream and re-run the _Dataset Validator_ check for this PR after.

**Review by mguaypaq — COMMENTED** [review]
Once I can get the _Dataset Validator_ check to pass, this looks like it can be merged.

**Review by mguaypaq — APPROVED** [review]

**Comment by sandrinebedard** [comment]
Is there any update on this problem? Thanks!

**Comment by mguaypaq** [comment]
Sorry, I haven't had time to work on fixing the Dataset Validator. But:
* I've looked into it enough to see that this is because of various bugs in the Dataset Validator, which will take some time to fix; and
* Clearly just renaming the files should not affect the things that the Dataset Validator is supposed to be checking anyway.

So, I'll override the check and merge this change now, and open a separate issue for fixing the Dataset Validator.

**Pull request merged**
