### PR TITLE
Added yml config file with subjects to exclude

### PR DESCRIPTION
**Pull request by valosekj**
yml file contains also comments why subjects are removed from analysis

### CODE REVIEW

**Comment by jcohenadad** [comment]
@kousu this file was added using pure git (not git-annex). Is it ok to rebase and merge via github or should i manually sync this file with git-annex on my end?

**Review by jcohenadad — COMMENTED** [review]
- can you please call the file with small letters
- did you make sure the in-line comments are working with the yaml parser?
- if working with the parser, could you please systematically add two spaces between the value and the beginning of the comment

**Comment by valosekj** [comment]
> * can you please call the file with small letters

sure, I'll update filename

> * did you make sure the in-line comments are working with the yaml parser?

Yes, I did. I tested inline comments with pyyaml parser (which we use) and it looks it works without any problems.

> * if working with the parser, could you please systematically add two spaces between the value and the beginning of the comment

okay, so far, i used tab. Interestingly, somewhere, tab looks like one space, somewhere like two spaces.
I will change tab for two spaces everywhere.

**Comment by valosekj** [comment]
@jcohenadad probably should be ready for review. (Travis failed, but from its _Details_ page, I can see reason).
I implemented your suggestions:

> > * can you please call the file with small letters
> 
> sure, I'll update filename
> 

I updated filename to lowercase.


> > * if working with the parser, could you please systematically add two spaces between the value and the beginning of the comment
> 
> okay, so far, i used tab. Interestingly, somewhere, tab looks like one space, somewhere like two spaces.
> I will change tab for two spaces everywhere.

I added two spaces between sub_IDs and inline comments

**Review by jcohenadad — CHANGES_REQUESTED** [review]
file should be excluded from the BIDS validator to avoid:

https://travis-ci.com/github/spine-generic/data-multi-subject/builds/180513459#L578

**Comment by valosekj** [comment]
> file should be excluded from the BIDS validator to avoid:
> 
> https://travis-ci.com/github/spine-generic/data-multi-subject/builds/180513459#L578

Thanks 👍 I fixed this in the last commit https://github.com/spine-generic/data-multi-subject/pull/11/commits/b6921195b23d56d7ca1bfe49381f259eb5de04c1

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
