### PR TITLE
Refractor derivatives naming convention

### LINKED ISSUE #141: Rename `seg-manual` to `label-SC_seg-manual`
Based on our new [convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#derivatives-structure), we can consider renaming of:

`sub-amu01_T1w_seg-manual.nii.gz`

to:

`sub-amu01_T1w_label-SC_seg-manual.nii.gz`

We can also consider renaming `derivatives/labels` to `derivatives/manual_labels`. Then, we could omit `-manual` from the file names, for example: `sub-amu01_T1w_label-SC_seg.nii.gz`

### LINKED ISSUE #144: Some subjects have different image and label dimensions and resolution
Some subjects have different image and label dimensions and resolution. 

For example, for subject `sub-beijingGE02`, T2w image has different `dim` and `pixdim` than T2w spinal cord segmentation:

 ```console
$ sct_image -i sub-beijingGE02/anat/sub-beijingGE02_T2w.nii.gz -header | grep dim | head -2
dim		[3, 56, 256, 256, 1, 1, 1, 1]
pixdim		[1.0, 0.8, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]

$ sct_image -i derivatives/labels/sub-beijingGE02/anat/sub-beijingGE02_T2w_seg-manual.nii.gz -header | grep dim | head -2
dim		[3, 56, 320, 320, 1, 1, 1, 1]
pixdim		[-1.0, 0.799994, 0.8, 0.8, 1.0, 1.0, 1.0, 1.0]
```

This discrepancy probably originates from [processing](https://github.com/spine-generic/spine-generic/blob/c8c8408715f101414ca08c6bcf29a5d5b87df90a/process_data.sh#L177-L183), where `T2w` image was resampled and then segmented:

```
# T2
# ------------------------------------------------------------------------------
file_t2="${SUBJECT}_T2w"
# Reorient to RPI and resample to 0.8mm iso (supposed to be the effective resolution)
sct_image -i ${file_t2}.nii.gz -setorient RPI -o ${file_t2}_RPI.nii.gz
sct_resample -i ${file_t2}_RPI.nii.gz -mm 0.8x0.8x0.8 -o ${file_t2}_RPI_r.nii.gz
file_t2="${file_t2}_RPI_r"
# Segment spinal cord (only if it does not exist)
segment_if_does_not_exist $file_t2 "t2"
```

In other words, [data-multi-subject](https://github.com/spine-generic/data-multi-subject) contains the original non-resampled T2w image but SC seg obtained from resampled T2w image. 
So far, I noticed this for `sub-beijingGE` and `sub-brnoUhb` subjects.

### LINKED ISSUE #147: Two T1w labels for some subjects
@NathanMolinier and I noticed that some subjects have duplicated T1w labels:

```console
data-multi-subject/derivatives/labels/sub-amu02/anat$ ls -1 *T1w*labels*nii.gz
sub-amu02_T1w_RPI_r_labels-manual.nii.gz
sub-amu02_T1w_labels-disc-manual.nii.gz
```

### `T1w_RPI_r_labels-manual.nii.gz`
These labels were created in the context of the spine-generic paper on the reoriented and resampled images (see lines [here](https://github.com/spine-generic/spine-generic/blob/c8c8408715f101414ca08c6bcf29a5d5b87df90a/process_data.sh#L149-L151)). These files contain only two labels at C3 and C5 **_mid-vertebral levels_** (because we used only two labels for the registration to the template), see lines [here](https://github.com/spine-generic/spine-generic/blob/c8c8408715f101414ca08c6bcf29a5d5b87df90a/process_data.sh#L71-L72). These labels are available only for 31 subjects (those where the automatic labeling did not work).

### `T1w_labels-disc-manual.nii.gz`
These labels were created manually by @NathanMolinier using the `manual-correction.py` script in the original images (i.e., no reorientation and resampling were applied). These files contain **_disc labels_** for all visible discs. These labels are available for **_all_** the subjects.

---

@NathanMolinier pointed out that it might be confusing to have two "labels" files.

Potential solutions: 
- clarify the difference between the label files in README.md
- suggestion from @NathanMolinier: remove `T1w_RPI_r_labels-manual.nii.gz` files

Related to https://github.com/spine-generic/data-multi-subject/issues/95

### LINKED ISSUE #151: Labels with missing suffixes
## Description

I noticed that for some subjects masks, suffixes are missing:
- derivatives/labels_softseg/sub-brnoCeitec01/anat/sub-brnoCeitec01_T1w.nii.gz
- derivatives/labels_softseg/sub-barcelona02/anat/sub-barcelona02_flip-1_mt-on_MTS.nii.gz
- derivatives/labels_softseg/sub-barcelona02/anat/sub-barcelona02_T2w.nii.gz
- derivatives/labels_softseg/sub-balgrist02/anat/sub-balgrist02_flip-1_mt-on_MTS.nii.gz

@sandrinebedard should we just add `_softseg` ?

### LINKED ISSUE #153: T1w image and its manual segmentation does not match in 3  sub-brnoUhb scans
I see 3 scans where manual T1w segmentation mismatch T1w image on the latest database release. It seems like qform and sform matrices needs tobe matched.

See yourself:
`cd data-multi-subject`
`fsleyes sub-brnoUhb02/anat/sub-*_T1w.nii.gz derivatives/labels/sub-brnoUhb02/anat/sub-*_T1w_seg-manual.nii.gz &`
`fsleyes sub-brnoUhb07/anat/sub-*_T1w.nii.gz derivatives/labels/sub-brnoUhb07/anat/sub-*_T1w_seg-manual.nii.gz &`
`fsleyes sub-brnoUhb08/anat/sub-*_T1w.nii.gz derivatives/labels/sub-brnoUhb08/anat/sub-*_T1w_seg-manual.nii.gz &`

I have not checked T2w and T2star segmentation for these subjects. There may be the same issue.

This issue impacts quality of process_data.sh outcomes as noted [here](https://github.com/spine-generic/spine-generic/issues/274)

### LINKED ISSUE #156: Add processed images in the derivatives folder
## Description
Since the labels in the derivatives were generated from preprocessed images (reorientation, resampling, etc.), to avoide confusion and issues such as #153 and repeating these steps, we propose to include the preprocessed images inside the derivatives folder in a sub-folder. 

## Suggestion
* Add the preprocessed images in : `derivatives/processed_data`  (we can discuss on better names)
* Include in the README of `derivatives/processed_data` a link to a release of the dataset and preprocessing script used to create these images

## Tasks:

* add dataset description
* add readme (and link to processing script)
* add suffix `space-other`
* add suffix description `space-other `in all json 
* create json sidecar for dwi rec-average
## Relevant issues:

#144
#153

### LINKED ISSUE #157: Refractor derivatives naming convention
## Description
Since we have now [clarified ](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#building-the-derivatives-datasets)the naming of the labels in the derivatives, we need to update the derivatives name in spine generic

## Suggestions

* `sub-amu01_T2star_seg-manual.nii.gz` --> `sub-amu01_T2star_label-SC_seg.nii.gz`
* `sub-amu01_T2w_labels-disc-manual.nii.gz` --> `sub-amu01_T2w_label-discs_dlabel.nii.gz`
* `sub-amu01_T1w_softseg.nii.gz` --> `sub-amu01_T1w_label-SC_softseg.nii.gz`
* `sub-amu01_T1w_softseg_bin.nii.gz` --> `sub-amu01_T1w_desc-softseg_label-SC_seg.nii.gz`  (to be discussed)
* `sub-amu01_T1w_csfseg-manual.nii.gz` --> `sub-amu01_T1w_label-CSF_seg.nii.gz`
* For discs warped from T2w: `sub-amu01_T2w_label-discs_desc-warp_dlabel.nii.gz`
* `_RPI_r_labels-manual` --> `space-other_T2w_label-vertebrae_desc-C2C5_dlabel`
* `gmseg `--> `label-GM_seg`

**Note**: do we want to add the discs labels from warping from T2w for the other contrasts inside the derivatives? (as we do and need for the contrast-agnostic project)

## Related issues
#156 
#154
#141

## TODO

* Update all preprocessing scripts with new name convention

### PR DESCRIPTION
**Pull request by sandrinebedard**
## Description

This PR adresses #156 and #157 mainly and cleans up the datasets. Th main changes include:

1. Adds preprocessed images with entity `space-other` in folder `derivatives/data_preprocessed`: (#156, #144 )
    * `T1w`: Reoriented to RPI and resampled to 1x1x1 mm
    * `T2w`: Reoriented to RPI and resampled to 0.8x0.8x0.8 mm
    * `T2star`: Reoriented to RPI and root mean square across 4th dimension (if exists)
    * `MTS`: Reoriented to RPI
    * `DWI`:   Mean image across directions after motion correction
2. Add `labels_seftseg_bin` in the derivatives
3. Add warp T2w disc labels for MTS, T2star and DWI data in `derivatives/labels`
4. Renaming of derivatives
    * `sub-amu01_T2star_seg-manual.nii.gz` --> `sub-amu01_space-other_T2star_label-SC_seg.nii.gz` (#141)
    * `sub-amu01_T2w_labels-disc-manual.nii.gz` --> `sub-amu01_T2w_label-discs_dlabel.nii.gz`
    * `sub-amu01_T1w_softseg.nii.gz` --> `sub-amu01_space-other_T1w_label-SC_softseg.nii.gz`
    * `sub-amu01_T1w_softseg_bin.nii.gz` --> `sub-amu01_space-other_T1w_desc-softseg_label-SC_seg.nii.gz`
    * `sub-amu01_T1w_csfseg-manual.nii.gz` --> `sub-amu01_space-other_T1w_label-CSF_seg.nii.gz`
    * For discs warped from T2w: `sub-amu01_T2w_label-discs_desc-warp_dlabel.nii.gz`
    * `sub-amu01_T2w_RPI_r_labels-manual.nii.gz` --> `sub-amu01_space-other_T2w_label-vertebrae_desc-C2C5_dlabel.nii.gz` (#147 )
    *  `sub-amu01_T2star_gmseg.nii.gz `--> `sub-amu01_space-other_T2star_label-GM_seg.nii.gz`
4. Remove duplicated files as described in #151
5. Update json sidecar with updated entities
6. Added spinal canal segmentations

## Remaining tasks

- [x] UPdate GM segmentation
- [ ] Add in readme link of script for SC canal seg
- [x] Add README for `data_preprocessed` with link to the script
- [x] Add README for `labels_softseg_bin` with link to the script
- [x] Update contrast-agnostic script and spine-generic analysis scripts with updated names and create a release

## Related Issues

Fixes #156 
fixes #157 
fixes #147
Fixes #144 
Fixes #153 
Fixes #141
Fixes #151

### CODE REVIEW

**Comment by valosekj** [comment]
Cross-referring an older issue: https://github.com/neuropoly/idea-projects/issues/1

**Comment by sandrinebedard** [comment]
Th PR is now ready for review!

**Comment by valosekj** [comment]
Thanks for this massive PR @sandrinebedard! 💯 

ad 1)
I randomly selected one subject (`sub-balgrist01`) and checked its files under data_preprocessed (`derivatives/data_preprocessed/sub-balgrist01`). Images look good -- they are reoriented to RPI and resampled.
I just noticed that `flip-1_mt-off_MTS.nii.gz` is missing under `derivatives/data_preprocessed`:

```console
valosek@macbook-pro:~/data/data-multi-subject$ ls -1 sub-balgrist01/anat/sub-balgrist01_flip-*.nii.gz
sub-balgrist01/anat/sub-balgrist01_flip-1_mt-off_MTS.nii.gz
sub-balgrist01/anat/sub-balgrist01_flip-1_mt-on_MTS.nii.gz
sub-balgrist01/anat/sub-balgrist01_flip-2_mt-off_MTS.nii.gz

valosek@macbook-pro:~/data/data-multi-subject$ ls -1 derivatives/data_preprocessed/sub-balgrist01/anat/sub-balgrist01_flip-*.nii.gz
derivatives/data_preprocessed/sub-balgrist01/anat/sub-balgrist01_flip-1_mt-on_space-other_MTS.nii.gz
derivatives/data_preprocessed/sub-balgrist01/anat/sub-balgrist01_flip-2_mt-off_space-other_MTS.nii.gz
```

ad 2,3,4,5,6)
looks good!

ad 7)
I found only 10 CSF canal segmetations. Just double-checking that this is correct?

```console
valosek@macbook-pro:~/data/data-multi-subject/derivatives$ find . -name "*CSF*nii.gz" | wc -l
      10
```

**Comment by sandrinebedard** [comment]
Thank you for reviewing @valosekj !
> I found only 10 CSF canal segmetations. Just double-checking that this is correct?
> 
> ```
> valosek@macbook-pro:~/data/data-multi-subject/derivatives$ find . -name "*CSF*nii.gz" | wc -l
>       10
> ```

My bad it should've been written SC canal in the PR description! You should find `label-canal_seg`

```
(base) sebeda@joplin:~/datasets/data-multi-subject/derivatives/labels$ find . -name "*canal*nii.gz" | wc -l
10
```
Regarding `flip-1_mt-off_MTS.nii.gz` are not used in contrats-agnostic and do not have any labels related to them, that is why this contrast is not there. Should we add them still?

**Comment by sandrinebedard** [comment]
> Regarding flip-1_mt-off_MTS.nii.gz are not used in contrats-agnostic and do not have any labels related to them, that is why this contrast is not there. Should we add them still?

We decided not to include, since there is not associated labels.

@mguaypaq I think we would be ready to merge!

**Comment by mguaypaq** [comment]
Hmm, in addition to the current problems with the Dataset Validator, it looks like it's now running out of disk space when trying to `git annex get` the dataset. I'll manually run as much of the validation steps as I can, then merge this PR anyway so that we don't have to wait too long.

**Comment by mguaypaq** [comment]
Ok:
* `git annex get` works fine.
* `bids-validator .` works fine (only irrelevant warnings).
* `.github/workflows/lint-tsv participants.tsv` works fine.
* I didn't run `sg_params_checker` or `sg_check_data_consistency`.

I'm going to merge this.

**Review by mguaypaq — APPROVED** [review]

**Comment by mguaypaq** [comment]
Ah, it looks like I can't bypass branch protections. I guess I'll fix the validator before merging this PR, in that case.

**Pull request merged**
