### PR TITLE
Fix software version

### PR DESCRIPTION
**Pull request by alexfoias**
The problem was reported by external collaborator on Oct 8, 2021

to merge after https://github.com/spine-generic/data-multi-subject/pull/109

### CODE REVIEW

**Comment by alexfoias** [comment]
I have checked the BIDSification script and everything seems fine.
These fields were added manually to the `participants.tsv` file, hence human error from dragging the cells.

**Review by jcohenadad — APPROVED** [review]
thanks for the fix!

**Review by jcohenadad — APPROVED** [review]

**Comment by jcohenadad** [comment]
@alexfoias can you pls update the branch

**Comment by alexfoias** [comment]
@jcohenadad I updated the branch.

**Comment by jcohenadad** [comment]
@alexfoias can you please update this PR after https://github.com/spine-generic/data-multi-subject/pull/112

**Review by jcohenadad — APPROVED** [review]

**Comment by jcohenadad** [comment]
at some point it would be great to make the validator more flexible because we keep merging with the validator failing...

**Comment by alexfoias** [comment]
We had an error because of the /scripts folder. Changed it to be compliant as per documentation https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#code

**Comment by alexfoias** [comment]
@jcohenadad the https://github.com/spine-generic/data-multi-subject/pull/97/commits/1bb0a3261b0c34c0583a309969299746abb21cf2 seemed to have fixed the issue. We can merge it.

**Pull request merged**
