### PR TITLE
Added disc labels for T1w and T2w

### PR DESCRIPTION
**Pull request by lrouhier**
This PR aims at adding files containing discs label for most subjects. 
All centers have been labeled except:
- fslPrima
- fslAchieva
- mountSinai

It also provides one minor correction to CONTRIBUTION.md.

### CODE REVIEW

**Comment by jcohenadad** [comment]
@lrouhier could you please attach the QC report of these added derivatives, for easy review and track record (the reports are always attached to new releases). Thanks

**Comment by lrouhier** [comment]
Qc folder: https://drive.google.com/drive/folders/1_HB7tpg-G_Xq6tQ_nQ1XatBKk8lXSNRf?usp=sharing

**Comment by jcohenadad** [comment]
> Qc folder: https://drive.google.com/drive/folders/1_HB7tpg-G_Xq6tQ_nQ1XatBKk8lXSNRf?usp=sharing

@lrouhier could you instead point to a zipped file (otherwise the google drive API needs to do the zip each time a download is requested-- which is a waste of time)-- thanks

**Comment by lrouhier** [comment]
Here is a zip link to the qc: https://drive.google.com/file/d/1wDNaCKI4SaTJVmzS_v-zez0SIHdJyEzW/view?usp=sharing

**Comment by jcohenadad** [comment]
damn! travis gets stuck with a timeout, which we didn't get in the past (i already restarted the job):
https://travis-ci.com/github/spine-generic/data-multi-subject/builds/181479798#L563

**Comment by lrouhier** [comment]
Yes I saw ! Then again that's 484 more files, even if it's not that heavy (because it's just label) I'm guessing it's still adding like a minute or two which might be enough to go overboard. 
I'm guessing is due to the fact that the job has no log output (https://docs.travis-ci.com/user/customizing-the-build#build-timeouts), because we use a quiet mode and it takes more than 10 minutes now so it is shutting down.

**Comment by jcohenadad** [comment]
@lrouhier i've noticed a few problems:
- On the T2w images, the labels are often placed too inferiorly with respect to the posterior tip of the disc
- On the T2w images, some labels are placed inside the central canal (instead of the posterior tip)
- Some labels are missing where discs are visible

I haven't reviewed all of them (only the first ~10%), but I expect the same problem is present in the remaining 90%.

Here are some screenshots of notable problems: [problem_discs.zip](https://github.com/spine-generic/data-multi-subject/files/5132836/problem_discs.zip)

**Comment by lrouhier** [comment]
Yes I saw. I am correcting that.

Might be due to the fact that I did not label on the same slice as the displayed slice (which can cause a few pixels of difference)

**Comment by jcohenadad** [comment]
> Might be due to the fact that I did not label on the same slice as the displayed slice (which can cause a few pixels of difference)

ah! good point. Can you please verify if the displayed slice is the same as the one you used, and if not, let's fix that first

**Comment by lrouhier** [comment]
I checked and it does not seem to be that. I am honestly a bit confused. I Check my "straight" label that usually use and these are correct. SO I may have worked with T2 registered to T1 to try and use the T1 label and then corrected on either the T2 registered to T1 or the straighten image. In any case, all the labels have been corrected I will produce the qc In a minute just after I update this PR (so that the data matches the QC)

**Comment by jcohenadad** [comment]
@kousu can we authorize "squash and merge" for the repos, so the addition/deletion of binaries in non-master branches can be "forgotten" from the history tree?

**Comment by lrouhier** [comment]
Here is the qc: https://drive.google.com/file/d/1UHgTXPH2JsDxGalybxrRcnJXwvVRM06G/view?usp=sharing

**Comment by lrouhier** [comment]
FYI: with the correction we added the missing subjects so all should be labeled.

**Comment by jcohenadad** [comment]
@PaulBautin could you please review?

**Comment by PaulBautin** [comment]
@lrouhier, I'm not finished reviewing but i came across this image. I guess this is just due to the QC image slice:
image

**Comment by jcohenadad** [comment]
> @lrouhier, I'm not finished reviewing but i came across this image. I guess this is just due to the QC image slice:
> image

indeed, this is a known problem. This PR needs to be ported from the old repos to the new repos: https://github.com/spine-generic/data-multi-subject_DO-NOT-USE/pull/23

I'll do it when i find a minute

**Comment by jcohenadad** [comment]
defacing problem addressed in https://github.com/spine-generic/data-multi-subject/pull/19.

**Comment by lrouhier** [comment]
New qc -->https://drive.google.com/file/d/1LHdernT1sW350IMQ0uSc0mcC_KxP0uLw/view?usp=sharing
 sub-Tokyo750w01 now with more label (as per request by @PaulBautin) Tell me it is good now!

**Comment by PaulBautin** [comment]
Ok, everything looks great. Thanks @lrouhier ! Once this PR and PR #19 are merged we will be ready for a new csa-atrophy processing.

**Review by jcohenadad — APPROVED** [review]
Looks great 👍  Thank you @lrouhier for this awesome contribution!! 🏅

**Pull request merged**
