### PR TITLE
Replaced `-` by `n/a` in participants.tsv for BIDS compliance

### LINKED ISSUE #89: Substitute dash with n/a in the participants.tsv
Same issue was encountered with sct-testing-large.

See: https://github.com/ivadomed/ivadomed/issues/796

### PR DESCRIPTION
**Pull request by alexfoias**
Ran this script to do the change:

```
import pandas as pd
df = pd.read_table("/Users/alex/data/data-multi-subject/participants.tsv", encoding="ISO-8859-1")

df_new = df.replace("-", "n/a")
df_new.to_csv("/Users/alex/data/data-multi-subject/participants.tsv", sep='\t', index=False)

```

Fixes https://github.com/spine-generic/data-multi-subject/issues/89

### CODE REVIEW

**Comment by alexfoias** [comment]
I saw that this removed some " from some fields. @mpompolas could you please check if it breaks something in your pipeline ?

**Comment by kousu** [comment]
I think pandas is correct here. Those fields should not have had quotes in them.

**Review by kousu — APPROVED** [review]

**Comment by alexfoias** [comment]
@kousu @jcohenadad can we merge this one ?

**Comment by jcohenadad** [comment]
does pybids work on this new participants.tsv?

**Comment by alexfoias** [comment]
Tested it here: https://pastebin.com/eNNPy8kq

**Review by jcohenadad — APPROVED** [review]

**Comment by jcohenadad** [comment]
@alexfoias can you pls resolve conflicts

**Comment by alexfoias** [comment]
@kousu I've realized that I did a mistake and I want to drop the previous commit https://github.com/spine-generic/data-multi-subject/pull/91/commits/ac4681a5661ac2cd40326e5ca760837c679fc70c not sure how to do it without breaking things. Could you please help me ? thanks

**Comment by alexfoias** [comment]
@jcohenadad we are ready to merge this one.

**Review by jcohenadad — APPROVED** [review]
thx guys!

**Comment by jcohenadad** [comment]
@alexfoias can you please update this PR after #112

**Comment by alexfoias** [comment]
@jcohenadad we can abandon this PR and not merge because the master already has `n/a`.

**Pull request closed without merging**
